apiVersion: v1
kind: Service
metadata:
  name: x1api-k8s
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: x1api-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x1api-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: x1api-k8s
  template:
    metadata:
      labels:
        app: x1api-k8s
    spec:
      containers:
        - name: x1api-k8s
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8081